### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by twopirllc** [hackingthemarkets/pandas-ta-tutorial#1]
Hello @hackingthemarkets,

Thanks for featuring Pandas TA Library recently! I appreciate it!! 😎 

Pandas TA, as you may already know, has more features under the hood than what you covered in the YT video. Based on what you covered, you can also easily download with _yfinance_ **and** automatically append/concat the indicators to the _ohlcv_ DataFrame with ```append=True``` argument.

```python
import ccxt
import pandas as pd
import pandas_ta as ta
from datetime import datetime

to_dt = lambda x: datetime.utcfromtimestamp(float(x) / 1000.0)

# DL and clean up
exchange = ccxt.binance()
bars = exchange.fetch_ohlcv("ETH/USDT", limit=100)
df = pd.DataFrame(bars, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
ts = df["timestamp"].apply(to_dt)
df.set_index(pd.DatetimeIndex(ts), inplace=True)
df.drop(columns=["timestamp"], inplace=True)

# Apply and Append TA
df.ta.adx(length=10, append=True)
df.ta.macd(append=True)
df.ta.rsi(append=True)

# Sanity Check
print(df)
```

Also with _yfinance_ installed, you can do:

```python
import pandas_ta as ta

df = ta.df.ta.ticker("AAPL", period="1mo")

# Apply and Append TA
df.ta.adx(length=10, append=True)
df.ta.macd(append=True)
df.ta.rsi(append=True)

# Sanity Check
print(df)
```

Keep up the good work helping and educating users and developers creating their own systems!

Kind Regards,
KJ

**Comment by hackingthemarkets** [comment]
@twopirllc I appreciate the feedback! Thanks so much for this library, it is so easy to use. I'll be using it in more videos for sure, so will apply your comments in future tutorials. I'm interested in exploring the backtesting and Strategy sections, so will be doing a follow up later :).

**Comment by twopirllc** [comment]
@hackingthemarkets,

>  I appreciate the feedback! Thanks so much for this library, it is so easy to use.

No worries. Mission accomplished! 😄 

> I'll be using it in more videos for sure, so will apply your comments in future tutorials.

Looking forward to it!

> I'm interested in exploring the backtesting and Strategy sections, so will be doing a follow up later :)

Nice. 😄 

When using a Strategy and just using a just a _few_ indicators, set ```df.ta.cores = 0``` so it does not waste time setting up and running the multiprocessing Pool. If you are using a lot of indicators, then adjust the ```cores``` as needed.

For backtesting, VectorBT does a better job. 😎 

Let me know if you have any questions.

Happy 4th!
KJ
